### ISSUE TITLE
Dropping from 90fps to 9fps

### ISSUE THREAD

**Issue by greensad** [Haven-King/Atmosfera#12]
1.16.4, latest fabric + fabric api + Atmosphera 1.3.5
When the latest version of the mod is installed my framerate tanks from around 90fps to 9fps. When this mod is removed frame rate  jumps back up to 90.

**Comment by zFerry98** [comment]
I add myself.
With MultiMC on Develop, Java 11 (openJDK), Java 8 271 x64
16GB Ram ddr3
I7 7700HQ
GTX 1060Ti Mobile

MC: 1.16.4
Fabric loader 0.10.8
Fabric loader 0.10.7

From 90 - 100 fps it drops to 7/9.
However an interesting thing is that if I start minecraft (javaw.exe) with the Intel HD this problem does not seem to exist (40 50 fps) with 16 of render distance and all the various texture packs.

<details>
 <summary>Loaded Mods:</summary>

Mods:
  [✔️] advancements-enlarger-0.2.3
  [✔️] appleskin-mc1.16-fabric-1.0.11
  [✔️] atmosfera-1.3.5
  [✔️] audiooutput-1.16.2-0.0.3
  [✔️] authme-1.16.3-1.4.0
  [✔️] Autofish-0.9.1-fabric-mc1.16.4
  [✔️] betterworldlist-1.0.4-1.16.2
  [✔️] blockmeter-1.2.0-fabric-1.16.3
  [✔️] borderless-mining-1.0.6+1.16.2
  [✔️] crawl-0.8.1
  [✔️] durabilityviewer-1.16.4-fabric0.25.1-1.10
  [✔️] dynamic-fps-1.2.1
  [❌] DynamicSoundFilters-1.1.3+1.16.2.jar (disabled)
  [✔️] easierchests-1.16.4-fabric0.25.1-1.6.2
  [✔️] euclid-1.2
  [✔️] fabric-api-0.28.4+1.16
  [❌] fabric-api-0.29.2+1.16.jar (disabled)
  [✔️] fabric-gamesense-mod-1.0.1
  [✔️] fabric-language-kotlin-1.4.21+build.1
  [✔️] fabricmod_VoxelMap-1.10.14_for_1.16.4
  [✔️] GameInfo-mod-1.5.4+1.16.4
  [✔️] horse-stats-vanilla-4.1.4
  [✔️] hwyla-addon-horseinfo-0.2.2-1.16.1
  [✔️] Hwyla-fabric-1.16.2-1.9.23-79
  [✔️] inventoryprofiles-forge-1.16.2-0.4.2
  [✔️] light-overlay-5.5.4
  [❌] lithium-fabric-mc1.16.4-0.6.0.jar (disabled)
  [📁] mamiyaotaru (folder)
  [✔️] Missing+Bits-v1.16.3+Fabric+b1
  [✔️] MixinBootstrap-1.0.5
  [✔️] modmenu-1.14.13+build.19
  [✔️] modupdater-1.1.11+1.16.2-rc2
  [✔️] notenoughcrashes-2.1.4+1.16.4
  [✔️] optifabric-1.8.13
  [❌] OptiFine_1.16.4_HD_U_G5.jar (disabled)
  [✔️] orderly-2.0.0-alpha.10-1.16
  [✔️] phosphor-fabric-mc1.16.3-0.7.0+build.10
  [✔️] preview_OptiFine_1.16.4_HD_U_G6_pre8
  [✔️] rer-2.1.3
  [✔️] RoughlyEnoughItems-5.8.10
  [✔️] shulkerboxtooltip-2.3.3+1.16.4
  [✔️] XaerosWorldMap_1.11.6_Fabric_1.16.4

Params:
  --username  --version MultiMC5 --gameDir D:/Programmi/MultiMC/instances/Fabric Latest 1.16.3/.minecraft --assetsDir D:/Programmi/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: 1366 x 850

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2048m, -Xmx8064m, -Duser.language=en]


Id del Processo di Minecraft: 16784


Using onesix launcher.

</details>
