### ISSUE TITLE
Game crashes when opening F3 with Debug Pie

### ISSUE THREAD

**Issue by NebelNidas** [Haven-King/Atmosfera#14]
When pressing `Shift` + `F3` to open the debug screen with debug pie, Minecraft crashes. This issue was introduced in v1.3.5, v1.3.3 works fine.

**Comment by 2mal3** [comment]
I have the same problem. [Here](https://pastebin.com/SsXZBR1f) is my crash report.

**Comment by GlennSchner** [comment]
Same issue, confirmed it's not a mod compatibility issue by removing all other mods except libraries, Fabric essential mods, and optifine. Crash report here: https://paste.ee/p/NikOH
