### ISSUE TITLE
Crash when entering the nether.

### ISSUE THREAD

**Issue by tyukara** [Haven-King/Atmosfera#17]
installed mods
  Fabric Loader 0.11.3
  Atmosfera 1.4.0+mc1.16.5
  Cloth Config v4 4.11.26
  Fabric API 0.36.0+1.16
launcher
  MutiMC5 0.6.12-1540(java 16.0.1)
crash log
https://paste.ee/p/nxJ03

**Comment by tyukara** [comment]
It's been fixed and now it doesn't crash anymore.
Thank you for the hasty correction.

**Comment by tyukara** [comment]
I updated the server and client versions to 1.17.1, and the same error occurred again.
The error message appears to be the same.
The log is below.

https://paste.ee/p/2uzPS

**Comment by Zetabite** [comment]
Try using 1.4.2 version, the code as is should not under any circumstance even get there where it went if your crash is true

**Comment by tyukara** [comment]
I used atmosfera1.4.2 and the error was resolved.
Thanks a lot!
