### ISSUE TITLE
Random crashes (subtitle-related?)

### ISSUE THREAD

**Issue by madimura20** [Haven-King/Atmosfera#19]
For some reason whenever I play with this mod it often crashes at random times. Not Enough Crashes cannot identify a mod that's causing the crashes, but the log seems to indicate something related to subtitles. I first thought it was because of Hydrogen or Presence Footsteps, but the crash still happens even without those mods, even with the latest Java version, Fabric Loader and Fabric API.

Crash log: [https://paste.ee/p/Bo51e](https://paste.ee/p/Bo51e)

Installed mods:
Fabric Loader
Fabric API
Fabric Language Kotlin
Canvas Renderer
Lithium
Hydrogen
Human Reborn
Earth2Java
Decorative
Cave Biomes
Promenade
Decorative
Adorn
On Soul Fire
Wildfire Female Gender Mod
Winged
Better Dropped Items
ExtraSounds
Croptopia
FallingTree
Mod Menu
Elemental Creepers
Pettable
Command Macros
Inmis
Dawn API
Better Nether
Culinaire
Emotecraft
Mo Structures
Stoneholm
Cloth Config 5.0.34
LambDynamicLights
Trinkets
VanillaPlus Biomes
All the Blocks you Want
Blockus
WTHIT
Megane
Not Enough Crashes
Sentimentality 3
Xaero's Minimap

Let me know if there's anything else I need to add.

**Comment by madimura20** [comment]
Also sorry if the link acts weird, try copying and pasting it

**Comment by Haven-King** [comment]
I am unable to recreate this crash, unfortunately, which makes it pretty hard to track down a cause. Is there any specific situation where this happens?

**Comment by madimura20** [comment]
> 
> 
> I am unable to recreate this crash, unfortunately, which makes it pretty hard to track down a cause. Is there any specific situation where this happens?

I tried reinstalling the mod to see if the jar was corrupted, but even with the new jar I still get the same crash. However, it seems to me that it can happen when there is a large amount of SFX with subtitles playing at the same time, possibly overloading the subtitle HUD. For me its prone to happen most when I am falling or flying down to a cave with a lot of vegetation or water, due to the different plethora of sounds it generates. I feel like this may be an issue on Mojang or Java's end, but the crash log generated seems to be kind of vague.

Another crash log from reinstalled mod.
[https://paste.ee/p/gbcEk](url)

**Comment by Haven-King** [comment]
This should be fixed in the next version, which I'll try and publish in the next few days after I fix #20.
