### ISSUE TITLE
Extreme Lag

### ISSUE THREAD

**Issue by SharkieTV** [Haven-King/Atmosfera#21]
Hi, My players from my Modpack: [Medieval Minecraft [FABRIC]](https://www.curseforge.com/minecraft/modpacks/medieval-minecraft-fabric) have reported to me that your mod is causing bad fps lag, when removing the mod the modpack works perfectly fine but adding your mod makes them lag, so far 8 of them have reported it.

Using the latest 1.17 version and here is a log of one of the players if it helps
https://pastebin.com/jc69M8zB

**Comment by Lieutenant2014** [comment]
this happens on 1.16 as well, i've tested it

**Comment by Disguys** [comment]
The same problem occurs even on good PC

**Comment by Anoaxx** [comment]
same here

**Comment by SharkieTV** [comment]
damn these guys are really dont care about not responding to the biggest issue of their mod

**Comment by Anoaxx** [comment]
Or.. they don't have enough time to fix it or they don't know how to do it.

**Comment by Haven-King** [comment]
> damn these guys are really dont care about not responding to the biggest issue of their mod

Believe it or not, I have many other projects that I work on, most of which take higher priority than this one. That's not to say I don't care about this mod, but it does take a back seat to the things that other people rely on.

I am aware of the performance hits that Atmosfera brings. While there have been some improvements in the 2.0 codebase, and I have some ideas that could lead to more, querying thousands of blocks every tick is never going to be snappy.

**Comment by Anoaxx** [comment]
TL:DR: don't have time due to other projects

**Comment by Anoaxx** [comment]
Btw extreme lag is caused by rendering new chunks

**Comment by Haven-King** [comment]
Try [version 2.0.0](https://www.curseforge.com/minecraft/mc-mods/atmosfera/files/3413595). If the lag persists, please open a new issue.

**Comment by Anoaxx** [comment]
Love ya! <3
