### ISSUE TITLE
owl noises

### ISSUE THREAD

**Issue by supertakeru** [Haven-King/Atmosfera#25]
too many owl noises please remove/restrict allow configure them away

**Comment by ruvaldak** [comment]
I agree, they're a little obnoxious. Would love to be able to toggle them.

**Comment by Zetabite** [comment]
Could just add owls as seperate noise instance, then you can mute them via atmosfera menu in the settings

**Comment by Zetabite** [comment]
if you want to have it already, just download the source and make a zip from the contents of the dungeons folder. its luckily no big effort to change it
