### ISSUE TITLE
1.18 plans?

### ISSUE THREAD

**Issue by EysseW** [Haven-King/Atmosfera#33]

**Comment by mikenrafter** [comment]
This' by far the best SFX overhaul mod out there. Charmonium doesn't even come close!

Please update to 1.18, as this'd play so nicely with [Resounding](https://github.com/thedocruby/resounding).

**Comment by Anoaxx** [comment]
i think main author just unmaintained this mod...

**Comment by Zetabite** [comment]
life exists. i hope i ported to 1.18 correctly so you can enjoy the mod soon again

**Comment by Haven-King** [comment]
1.18 and 1.18.1 will be up soon courtesy of @Zetabite. 1.18.2 will require a good deal more work due to the way it refactors how tags work. I'm looking into that now.
