### ISSUE TITLE
Crash on startup on Fabric MC Version 1.18.2

### ISSUE THREAD

**Issue by archonxgames** [Haven-King/Atmosfera#35]
Crashlog:
[latest.log](https://github.com/Haven-King/Atmosfera/files/8596204/latest.log)

Crashes during startup of game, unknown reason as to why

**Comment by Haven-King** [comment]
Do note that only 1.18 and 1.18.1 are listed as supported on CurseForge. MC underwent some pretty big changes in 1.18.2, and will require some additional changes to work.

**Comment by Anoaxx** [comment]
The file on [curseforge](https://www.curseforge.com/minecraft/mc-mods/atmosfera/files/3761126) shows that mod don't support 1.18.2 yet. I think its not a coincidence. @Haven-King if i can suggest something you can inform people on the page that you are working on 1.18.2 to save time for people. what do you think about it?(i can open another issue for this if you want)

**Comment by EGOIST1372** [comment]
@Haven-King Hi
Any update on 1.18.2 ? I don't want ETA just need an update on the progress
thanks <3
